{
  "arch": "x86_64",
  "build": "py38he6710b0_0",
  "build_number": 0,
  "channel": "https://conda.anaconda.org/anaconda/linux-64",
  "constrains": [],
  "depends": [
    "libgcc-ng >=7.3.0",
    "libstdcxx-ng >=7.3.0",
    "python >=3.8,<3.9.0a0",
    "unixodbc >=2.3.7,<2.4.0a0"
  ],
  "extracted_package_dir": "/home/jatin/anaconda3/pkgs/pyodbc-4.0.30-py38he6710b0_0",
  "features": "",
  "files": [
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/INSTALLER",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/LICENSE.txt",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/METADATA",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/RECORD",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/WHEEL",
    "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/top_level.txt",
    "lib/python3.8/site-packages/pyodbc.cpython-38-x86_64-linux-gnu.so"
  ],
  "fn": "pyodbc-4.0.30-py38he6710b0_0.tar.bz2",
  "license": "MIT",
  "license_family": "MIT",
  "link": {
    "source": "/home/jatin/anaconda3/pkgs/pyodbc-4.0.30-py38he6710b0_0",
    "type": 1
  },
  "md5": "8670f92d430f74326b0b3552148227c6",
  "name": "pyodbc",
  "package_tarball_full_path": "/home/jatin/anaconda3/pkgs/pyodbc-4.0.30-py38he6710b0_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/LICENSE.txt",
        "path_type": "hardlink",
        "sha256": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "sha256_in_prefix": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "size_in_bytes": 868
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "ab75cf0173e126f4f45ec4a1438e67e76ccd1e2fe43a023932fd7028cfaa02b1",
        "sha256_in_prefix": "ab75cf0173e126f4f45ec4a1438e67e76ccd1e2fe43a023932fd7028cfaa02b1",
        "size_in_bytes": 2134
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "d29fae849702418f508c966df88dbf255a6cf64ed2f820e8753cc0efa0d1d793",
        "sha256_in_prefix": "d29fae849702418f508c966df88dbf255a6cf64ed2f820e8753cc0efa0d1d793",
        "size_in_bytes": 645
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "4e915579717f700955d75f164883d6b63a96ee73efce83b0fb8f45992ddf0ca4",
        "sha256_in_prefix": "4e915579717f700955d75f164883d6b63a96ee73efce83b0fb8f45992ddf0ca4",
        "size_in_bytes": 103
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc-4.0.0_unsupported.dist-info/top_level.txt",
        "path_type": "hardlink",
        "sha256": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "sha256_in_prefix": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "size_in_bytes": 7
      },
      {
        "_path": "lib/python3.8/site-packages/pyodbc.cpython-38-x86_64-linux-gnu.so",
        "path_type": "hardlink",
        "sha256": "0d62a1eccd2b7cbb91e1348fc7af06e8a3cb98ed9ffa24deac0e3e361c64e41a",
        "sha256_in_prefix": "0d62a1eccd2b7cbb91e1348fc7af06e8a3cb98ed9ffa24deac0e3e361c64e41a",
        "size_in_bytes": 190288
      }
    ],
    "paths_version": 1
  },
  "platform": "linux",
  "requested_spec": "anaconda/linux-64::pyodbc==4.0.30=py38he6710b0_0",
  "sha256": "c06358d2fa278b3d297b742b56ab8c973645cf37aacbaf31d04a1e4aebd20717",
  "size": 74931,
  "subdir": "linux-64",
  "timestamp": 1581353596961,
  "track_features": "",
  "url": "https://conda.anaconda.org/anaconda/linux-64/pyodbc-4.0.30-py38he6710b0_0.tar.bz2",
  "version": "4.0.30"
}