pyodbc-4.0.0_unsupported.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyodbc-4.0.0_unsupported.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.0_unsupported.dist-info/METADATA,sha256=q3XPAXPhJvT0XsShQ45n52zNHi_kOgI5Mv1wKM-qArE,2134
pyodbc-4.0.0_unsupported.dist-info/RECORD,,
pyodbc-4.0.0_unsupported.dist-info/WHEEL,sha256=TpFVeXF_cAlV118WSIPWtjqW7nPvzoOw-49FmS3fDKQ,103
pyodbc-4.0.0_unsupported.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc.cpython-38-x86_64-linux-gnu.so,sha256=5lRkN8P6QydSplFFLp13y-tt8qqe0UpKSdB5GDX5bSY,190288
